# Generated by Django 4.2.5 on 2024-11-22 05:01

from django.db import migrations, models
import ecsite.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=ecsite.models.product.product_image_path),
        ),
    ]
