# Generated by Django 4.2.5 on 2024-11-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
