# Generated by Django 4.2.5 on 2024-12-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0007_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('discount_amount', models.PositiveIntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promotion_codes',
            },
        ),
    ]
