# Generated by Django 4.2.5 on 2024-12-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0008_promotioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promotion_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='ecsite.promotioncode'),
        ),
    ]
