# Generated by Django 4.2.5 on 2024-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0009_cart_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='割引額'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.PositiveIntegerField(default=0, help_text='商品合計'),
            preserve_default=False,
        ),
    ]
